version: '3.8'

services:
  commentator-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - prisma-data:/app/prisma
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-default_dev_secret_change_in_production}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  prisma-data:
    driver: local 